const data = {
    products:[
        {
            _id:'1',
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:120,
            countInStock: 10,
            brand:'Nike',
            rating:5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Lacoste Free Shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:90,
            countInStock: 10,
            brand:'Lacoste',
            rating:1.5,
            numReviews:120,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:500,
            countInStock: 10,
            brand:'Nike',
            rating:3.5,
            numReviews:20,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:120,
            countInStock: 10,
            brand:'Nike',
            rating:2.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:120,
            countInStock: 10,
            brand:'Nike',
            rating:3.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'Adidas Slim Shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:50,
            countInStock: 0,
            brand:'Adidas',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        }

    ]
};

export default data